const LOCAL_MULTIPLAYER_GAME = 'localMultiPlayer'
const LOCAL_SINGLEPLAYER_GAME = 'singlePlayer'
const ONLINE_MULTIPLAYER_GAME = 'onlineMultiPlayer'

export {LOCAL_MULTIPLAYER_GAME, LOCAL_SINGLEPLAYER_GAME, ONLINE_MULTIPLAYER_GAME}